### ISSUE TITLE
LinkedCellsReferences do not reinsert leaving particles properly

### ISSUE THREAD

**Issue by dmartin13** [AutoPas/AutoPas#791]
**Describe the bug**
When using the `LinkedCellsReferences` container some leaving particles are not reinserted properly in the container. The sanity check in `RegularGridDecomposition::exchangeMigratingParticles()` throws an exception: "All boundaries are periodic or reflective but ... migrants could not be re-inserted".
This is behavior is independent of the number of threads and appears reproducible in the same iteration (with the yaml file below).

After some investigation it has turned out that it is a problem with leaving particles, which are then suddenly present twice as owned particles in the container. The flow is roughly as follows: In iteration n, particle x is detected as leaving particle and set as dummy by `collectParticlesAndMarkNonOwnedAsDummy()`. In iteration n+1, the same particle is then added again in `LogicHandler::updateContainer()` by `collectLeavingParticlesFromBuffer()`. Afterwards, the cell structure is rebuilt in `LinkeCellsReference::updateDirtyParticleReferences() `and then the particle is suddenly present twice with the same position and velocity as owned particles, which in iteration n+2 leads to the fact that these particles then have position and velocity of `[-nan, -nan, -nan]` after position update and trigger the exception in `RegularGridDecomposition`.

Update: After digging into the code it turned out that this line of code in `LinkedCellsReferences::updateContainer()`  is responsible for doubling the particles (but this happens only with leaving particles that are reinserted by the `LogicHandler`):

```cpp
// multi layer swap-delete
// we copy the particle behind the last pointer in the cell over the particle we want to delete
**pIter = *particleVec.back();
```

**To Reproduce**
1. Clone 261878d
2. compile with `mkdir build && cd build && cmake .. && make md-flexible`
3. execute md-flexible with the yaml file below: `./md-flexible --yaml-filename input.yaml`
4. exception should appear (for me reproducible in iteration 286)

**Expected behavior**
No exception and no doubled owned particles in the container.

**Build environment:**
* OS: Ubuntu Server 20.04
* Compiler: gcc 11
* Build System: Make

**Additional context**
- The same yaml file runs without any problems when using LinkedCells as container.
- The parameters `verlet-rebuild-frequency` and `tuning-samples` affect the iteration number in which the exception is thrown.

**Input Yaml**
```yaml
container                        :  [LinkedCellsReferences]
traversal                        :  [lc_c08]
data-layout                      :  [A0S]
newton3                          :  [enabled]
verlet-skin-radius-per-timestep  :  0.025
verlet-cluster-size              :  4
cutoff                           :  2
box-min                          :  [0, 0, 0]
box-max                          :  [15, 60, 15]
cell-size                        :  [1]
deltaT                           :  0.00182367
iterations                       :  400
boundary-type                    : [periodic, periodic, periodic]
Sites:
  0:
    epsilon                      :  1.
    sigma                        :  1.
    mass                         :  1.
Objects:                         
  CubeClosestPacked:
    0:
      particle-type-id           :  0
      box-length                 :  [15, 6, 15]
      bottomLeftCorner           :  [0, 27, 0]
      particle-spacing           :  1.
      velocity                   :  [0, 0, 0]
no-flops                         :  false
no-end-config                    :  true
no-progress-bar                  :  false
vtk-filename                     :  LCvsLCRef
vtk-write-frequency              :  100
```
