### ISSUE TITLE
Understand the overhead of LinkedCellsReferences

### ISSUE THREAD

**Issue by SamNewcome** [AutoPas/AutoPas#799]
Understand the potential overhead of switching from the current container to reference-based containers.

Currently, with AoS, we see roughly the same performance between LinkedCells and LinkedCellsReferences (even without sorting). This is strange. Furthermore, even with sorting the difference in performance is small.

Investigate these effects by looking at cache misses vs runtime in the relevant parts of the simulation.

The conclusion of this issue is not some contribution to the code, but to understand fully the performance implications of reference-based containers, which is an important first step in the milestone Kokkos.

**Comment by dmartin13** [comment]
I have collected some (preliminary) data on this.
 
In the measurements, I compared the time for `iteratePairwise` and also tracked the accumulated number of particles that leave cells and go to other cells over the simulation. I wanted to investigate whether there is a correlation between performance and scattering of references. However, it does not seem as if there is a relationship here (see plots).

The scenario gradually increases the temperature to bring more movement into the whole system over time and thus increase the number of leaving particles. For the smaller simulation with about 30k particles, the difference between `LinkedCells` and `LinkedCellsReferences` is not very significant. In one case, even `LinkedCellsReferences` was (reproducibly) faster than `LinkedCells`.

To measure the cache misses I used perf: `perf stat -e cache-references,cache-misses`
(With `perf record` I unfortunately did not find a way to display the absolute number of `cache-references` and `cache-misses`. Otherwise I could have looked at the cache misses in individual functions. The values with `perf record` are always only relative percentages to the current execution, so it probably makes little sense to compare them with `perf diff`. In the logs with `perf record` that I looked at, however, it seems that most cache misses happen (as expected) in the `AoSFunctor`).

Executed on a Intel Xeon E5-2650 v2 with 20MB L3 cache

| NumParticles | NumThreads | Sorting  | Total Time to Solution (LC) | Total Time to Solution (LCRef) | (cache-misses/cache-references)*100 (LC) | (cache-misses/cache-references)*100 (LCRef) | Plot |
|--------------|------------|----------|-----------------------------|--------------------------------|------------------------------------------|---------------------------------------------|------|
| 31080        | 1          | disabled | 24.262s                     | 23.928s                        | 9.246 % of all cache refs                | 4.919 % of all cache refs                   |   [SmallNoSort1T](https://github.com/AutoPas/AutoPas/files/14529646/plotLCvsLCRefOut.pdf)   |
| 31080        | 1          | enabled  | 15.374s                     | 15.647s                        | 7.792 % of all cache refs                | 2.944 % of all cache refs                   |   [SmallSort1T](https://github.com/AutoPas/AutoPas/files/14529648/plotLCvsLCRefOut.pdf)   |
| 31080        | 8          | disabled | 3.665s                      | 4.341s                         | 2.739 % of all cache refs                | 1.213 % of all cache refs                   |    [SmallNoSort8T](https://github.com/AutoPas/AutoPas/files/14529649/plotLCvsLCRefOut.pdf) |
| 31080        | 8          | enabled  | 2.752s                      | 3.372s                         | 2.600 % of all cache refs                | 0.939 % of all cache refs                   |   [SmallSort8T](https://github.com/AutoPas/AutoPas/files/14529650/plotLCvsLCRefOut.pdf)   |

What is interesting here is that it does not seem as if the differences in runtime are caused by the cache misses, since `LincedCellsReferences` had less cache misses but in most cases a higher runtime.

I was then interested in larger simulations to investigate the differences when there are more particles than the cache can hold. The corresponding scenario is essentially the same, only with ~1.2Mio particles and a slightly adjusted `verlet-skin-radius-per-timestep`.
Here the difference between `LinkedCells` and `LinkedCellsReferences` becomes clearer.

| NumParticles | NumThreads | Sorting  | Total Time to Solution (LC) | Total Time to Solution (LCRef) | (cache-misses/cache-references)*100 (LC) | (cache-misses/cache-references)*100 (LCRef) | Plot |
|--------------|------------|----------|-----------------------------|--------------------------------|------------------------------------------|---------------------------------------------|------|
| 1226040      | 1          | disabled | 2152.718s                   | 2179.729s                      | 62.417 % of all cache refs               | 77.948 % of all cache refs                  |   [BigNoSort1T](https://github.com/AutoPas/AutoPas/files/14529651/plotLCvsLCRefOut.pdf)   |
| 1226040      | 1          | enabled  | 885.227s                    | 925.358s                       | 63.723 % of all cache refs               | 77.075 % of all cache refs                  |  [BigSort1T](https://github.com/AutoPas/AutoPas/files/14529652/plotLCvsLCRefOut.pdf)    |
| 1226040      | 8          | disabled | 312.654s                    | 341.606s                       | 40.287 % of all cache refs               | 68.147 % of all cache refs                  |   [BigNoSort8T](https://github.com/AutoPas/AutoPas/files/14529655/plotLCvsLCRefOut.pdf)   |
| 1226040      | 8          | enabled  | 135.674s                    | 160.267s                       | 56.557 % of all cache refs               | 73.689 % of all cache refs                  |  [BigSort8T](https://github.com/AutoPas/AutoPas/files/14529657/plotLCvsLCRefOut.pdf)    |

Overall, there is a noticeable difference between the two containers for large simulations. In the large simulation, the cache miss rate of `LinkedCellsReferences` is always higher compared to `LinkedCells`, but I'm not sure whether this really leads to the longer runtime, as it is the other way around in the smaller simulation.

(Side Note: It's cool how strongly the sorting influences the performance for the big scenario)

And here are the scenarios:
Small:
```yaml
container                        :  [LinkedCells] #References
traversal                        :  [lc_c08]
data-layout                      :  [AoS]
newton3                          :  [enabled]
verlet-skin-radius-per-timestep  :  0.1
verlet-cluster-size              :  4
verlet-rebuild-frequency         :  5
cutoff                           :  2
box-min                          :  [0, 0, 0]
box-max                          :  [65, 10, 65]
cell-size                        :  [1]
deltaT                           :  0.00182367
iterations                       :  200
boundary-type                    : [periodic, periodic, periodic]
sorting-threshold                :  8 #100000
Sites:
  0:
    epsilon                      :  1.
    sigma                        :  1.
    mass                         :  1.
Objects:                         
  CubeClosestPacked:
    0:
      particle-type-id           :  0
      box-length                 :  [60, 6, 60]
      bottomLeftCorner           :  [0, 3, 0]
      particle-spacing           :  1
      velocity                   :  [0, 0, 0]
thermostat:
 initialTemperature              :  0.000001
 targetTemperature               :  20
 deltaTemperature                :  0.8
 thermostatInterval              :  10
 addBrownianMotion               :  true
no-flops                         :  false
no-end-config                    :  true
no-progress-bar                  :  true
fastParticlesThrow               :  true
#no-progress-bar                  :  false
#vtk-filename                     :  LCvsLCRef
#vtk-write-frequency              :  1
```

Big:
```yaml
container                        :  [LinkedCells] #References
traversal                        :  [lc_c08]
data-layout                      :  [AoS]
newton3                          :  [enabled]
verlet-skin-radius-per-timestep  :  0.25
verlet-cluster-size              :  4
verlet-rebuild-frequency         :  5
cutoff                           :  2
box-min                          :  [0, 0, 0]
box-max                          :  [125, 64, 125]
cell-size                        :  [1]
deltaT                           :  0.00182367
iterations                       :  200
boundary-type                    :  [periodic, periodic, periodic]
sorting-threshold                :  8 #100000
Sites:
  0:
    epsilon                      :  1.
    sigma                        :  1.
    mass                         :  1.
Objects:                         
  CubeClosestPacked:
    0:
      particle-type-id           :  0
      box-length                 :  [120, 60, 120]
      bottomLeftCorner           :  [0, 3, 0]
      particle-spacing           :  1
      velocity                   :  [0, 0, 0]
thermostat:
 initialTemperature              :  0.000001
 targetTemperature               :  20
 deltaTemperature                :  0.8
 thermostatInterval              :  10
 addBrownianMotion               :  true
no-flops                         :  false
no-end-config                    :  true
no-progress-bar                  :  true
fastParticlesThrow               :  true
#no-progress-bar                  :  false
#vtk-filename                     :  LCvsLCRef
#vtk-write-frequency              :  1
```
