### ISSUE TITLE
deleteParticle Function in LinkedCells.h

### ISSUE THREAD

**Issue by xhulia028** [AutoPas/AutoPas#987]
**The bug**

On the branch **Fast-Particle-Buffer**, I was calling ```deleteParticle(Particle &particle)``` in LogicHandler.h's ```checkNeighborListsInvalidDoDynamicRebuild()``` function, to delete particles from the particle container.

```cpp
template <typename Particle>
void LogicHandler<Particle>::checkNeighborListsInvalidDoDynamicRebuild() {

  unsigned long _particleNumber = 0;

  const auto skin = getContainer().getVerletSkin();
  const auto halfSkinSquare = skin * skin * 0.25;

// Highlight: the vector to add the to be deleted particles
  std::vector<std::vector<std::reference_wrapper<Particle>>> toDelete(autopas_get_max_threads());

 AUTOPAS_OPENMP(parallel reduction(or : _neighborListInvalidDoDynamicRebuild))
  for (auto iter = this->begin(IteratorBehavior::owned | IteratorBehavior::containerOnly); iter.isValid(); ++iter) {
    const auto distance = iter->calculateDisplacementSinceRebuild();
    const double distanceSquare = utils::ArrayMath::dot(distance, distance);

      if (distanceSquare >= halfSkinSquare) {

      Particle& particle = *iter;
      Particle particleCopy = particle;

       _particleBuffer[autopas_get_thread_num()].addParticle(particleCopy);
       
       // Highlight: adding the references of the to be deleted particles to the buffer, so the changes can be reflected in the container
       toDelete[autopas_get_thread_num()].push_back(std::ref(particle));

        _particleNumber ++;

      }

  }

  _fastParticles = _particleNumber;
  for (auto t : toDelete) {
    for (auto &particleRef : t) {
      Particle& particle = particleRef.get();
      _containerSelector.getCurrentContainer().deleteParticle(particle);
    }
    
  }
}

```

```_containerSelector.getCurrentContainer().deleteParticle(particle)``` calls the respective ```deleteParticle(Particle &particle)``` function based on the current container. For other containers, particles are just marked as deleted instead of being actually removed from the container, but for LinkedCells and DirectSum they are popped using swap-delete.

I only used LinkedCells, so I’ll only focus on the ```deleteParticle(Particle &particle)``` function from LinkedCells.h:

```cpp
  bool deleteParticle(Particle &particle) override {
    // deduce into which vector the reference points
    auto &particleVec = _cellBlock.getContainingCell(particle.getR())._particles;
    const bool isRearParticle = &particle == &particleVec.back();
    // swap-delete
    particle = particleVec.back();
    particleVec.pop_back();
    return not isRearParticle;
  }
```
After debugging, I noticed that although I was passing the references of the particles to the ```deleteParticle(Particle &particle)``` function, one specific particle with ID 1290 always failed to be deleted.

Here are the screenshots from debugging:

1. In ```checkNeighborListsInvalidDoDynamicRebuild()```

In iteration 521, the particle with ID 1290, among other particles, is added to the particle buffer. Here is the copy of the original particle with ID 1290 in the particle buffer. 
(Note: in the particle buffer, a copy of the particle is added and not the actual one, so when it gets deleted, it can remain in the particle buffer.)

![Screenshot from 2024-12-16 13-34-50](https://github.com/user-attachments/assets/b9e5e0f6-a8a3-4865-b35b-8e05ead50eb2)

Here is the reference to the original particle with ID 1290 in the toDelete buffer:
![Screenshot from 2024-12-16 13-35-08](https://github.com/user-attachments/assets/4b8b706b-84fa-4be4-b36e-b1dd9999e0c6)

2. In deleteParticle(Particle &particle)
The particle was successfully passed to  ```deleteParticle(Particle &particle)```  and was found in the respective cell, as seen in the screenshots.
![Screenshot from 2024-12-16 13-36-15](https://github.com/user-attachments/assets/0bfcef51-ea8c-4aa5-9e30-bea8b40664bd)
![Screenshot from 2024-12-16 13-36-02](https://github.com/user-attachments/assets/92098edc-6d7d-42a7-b550-9b8fdb33e580)

2.1 After executing: ```cppparticle = particleVec.back();```
Here, we copy the particle at the end of particleVec to the memory location of the particle to be deleted, so we can pop the back and effectively remove the intended particle. However, as seen in the screenshots, the value of the variable _particle_ is updated, but the particle in particleVec at index 23 is not, and therefore doesn’t contain the values of particle 1262 in index 24.

![Screenshot from 2024-12-16 13-36-58](https://github.com/user-attachments/assets/8daf80fb-fa2c-4406-9c64-787bac0d02ba)
![Screenshot from 2024-12-16 13-37-03](https://github.com/user-attachments/assets/1b8a7b4d-46f2-4036-be1b-62ea297c2e5a)

2.2 After executing particleVec.pop_back();
Instead of popping particle 1290, since the previous line didn’t work, particle 1262 was popped instead. Hence, particle 1290 remains in the container. When the particles from the particle buffer are added back to the container, this particle gets duplicated. Additionally, particle 1262 was unjustly removed from the container.

![Screenshot from 2024-12-16 13-37-13](https://github.com/user-attachments/assets/30e7bc70-1d15-4d75-a54d-b9ff5d09c3b2)
![image](https://github.com/user-attachments/assets/404e5d6f-4ffb-4d8e-ba31-9ae6afc664e9)

Note:
I searched through the repository (specifically in the branch Fast-Particle-Buffer, which was created on top of Dynamic-VL-Merge), and noticed that the deleteParticle function was actually never really used, apart from being called in AutoPasImpl.h as part of AutoPas<Particle>::deleteParticle. There, it’s basically just making this function available for the end user to use. AutoPas<Particle>::deleteParticle is also never really called in the md-flexible example.

**To Reproduce**

To reproduce you can use this fallingDrop.yaml:
```yaml
container                        :  [LinkedCells, VerletLists, VerletListsCells, VerletClusterLists]
verlet-rebuild-frequency         :  1000
verlet-skin-radius               :  1.0
verlet-cluster-size              :  4
selector-strategy                :  Fastest-Absolute-Value
data-layout                      :  [SoA]
traversal                        :  [ lc_c08 ] 
tuning-strategies                :  []
tuning-interval                  :  2500
tuning-samples                   :  3
tuning-max-evidence              :  10
functor                          :  Lennard-Jones AVX
newton3                          :  [disabled, enabled]
cutoff                           :  3
box-min                          :  [0, 0, 0]
box-max                          :  [7.25, 7.25, 7.25]
cell-size                        :  [1]
deltaT                           :  0.0005
iterations                       :  15000
boundary-type                    :  [reflective,reflective,reflective]
globalForce                      :  [0,0,-12]
Sites:
  0:
    epsilon                      :  1.
    sigma                        :  1.
    mass                         :  1.
Objects:
  # "water"
  CubeClosestPacked:
    0:  
      particle-spacing           :  1.122462048
      bottomLeftCorner           :  [1, 1, 1]
      box-length                 :  [48, 28, 10]
      velocity                   :  [0, 0, 0]
      particle-type-id           :  0
  Sphere:
    0:  
      center                     :  [18, 15, 30]
      radius                     :  6
      particle-spacing           :  1.122462048
      velocity                   :  [0, 0, 0]
      particle-type-id           :  0
vtk-filename                     :  fallingDrop
vtk-write-frequency              :  1000
vtk-output-folder                :  vtkOutputFolder
no-end-config                    :  true
```
